Repository pknu-wap/wap-ui, pull requests merged in 2022-10, with the labels that each got.

#25 Feature/#24/code rule
  .commitlintrc.js
  .eslintrc.json
  .husky/commit-msg
  .husky/pre-commit
  package.json
  yarn.lock
Labels: bug, docs, feature

#27 feat: add color (#26)
  .eslintignore
  .prettierignore
  package.json
  packages/components/Button/Button.tsx
  packages/components/Checkbox/Checkbox.stories.tsx
  packages/components/Checkbox/Checkbox.tsx
  packages/components/Radio/Radio.stories.tsx
  packages/components/Radio/Radio.tsx
  packages/theme/common.ts
  packages/theme/theme-provider.tsx
  rollup.config.js
Labels: bug, feature

#33 Feature/#32/mediaquery breakpoints
  packages/theme/common.ts
  packages/theme/mediaQuery.ts
Labels: feature

#35 Refactor/#34/refactor eslint script and export folder
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  package.json
  packages/components/index.ts
  packages/index.ts
  packages/layouts/index.ts
  packages/theme/common.ts
  packages/theme/mediaQuery.ts
  packages/theme/theme-provider.tsx
Labels: refactor

#38 Feature/#31/modal component
  packages/components/Modal/Modal.stories.tsx
  packages/components/Modal/Modal.styles.ts
  packages/components/Modal/Modal.tsx
  packages/components/Modal/ModalBody.tsx
  packages/components/Modal/ModalCloseButton.tsx
  packages/components/Modal/ModalFooter.tsx
  packages/components/Modal/ModalHeader.tsx
  packages/components/Modal/index.ts
  packages/components/index.ts
Labels: feature
